services:
  ptoie_dep:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptoie_dep
    volumes:
      - .:/ptoie_dep
    command: poetry run python3 src/main.py -path ./inputs/wiki-200.txt -out ./out.json
    environment:
      - STANZA_RESOURCES_DIR=/ptoie_dep/.stanza_resources