services:
  ptoie_dep:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptoie_dep
    volumes:
      - .:/ptoie_dep
    command: poetry run python3 src/main.py -i /ptoie_dep/inputs/teste.conll -it conll -o /ptoie_dep/outputs/output.json -ot json -cc -sc -hs -a -t
    environment:
      - STANZA_RESOURCES_DIR=/ptoie_dep/models/.stanza_resources