services:
  ptoie_dep:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptoie_dep
    volumes:
      - .:/ptoie_dep
    command: poetry run python3 src/noie.py -path ./inputs/teste.txt
    environment:
      - STANZA_RESOURCES_DIR=/ptoie_dep/.stanza_resources