services:
  ptoie_dep:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptoie_dep
    volumes:
      - .:/ptoie_dep
    command: poetry run python3 src/main.py -path /ptoie_dep/inputs/ceten-200.conll -conll
    environment:
      - STANZA_RESOURCES_DIR=/ptoie_dep/.stanza_resources