name: extrai_fatos

on: [push, workflow_dispatch]

jobs:
  extrai_fatos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: DOCKER_BUILDKIT=1 docker build --tag ptoie_dep .
      - name: Run TESTE
        run: |
          docker run --rm -v $(pwd):/ptoie_dep ptoie_dep poetry run python3 src/noie.py -path ./inputs/teste.txt || true
          mv ./outputs/extractions.json ./outputs/teste.txt
      - name: Run CETEN200
        run: | 
          docker run --rm -v $(pwd):/ptoie_dep ptoie_dep poetry run python3 src/noie.py -path ./inputs/ceten-200.conll -conll || true
          mv ./outputs/extractions.json ./outputs/ceten-200.txt
      - name: Run WIKI200
        run: | 
          docker run --rm -v $(pwd):/ptoie_dep ptoie_dep poetry run python3 src/noie.py -path ./inputs/wiki-200.conll -conll || true
          mv ./outputs/extractions.json ./outputs/wiki-200.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fatos
          path: |
            ./outputs/ceten-200.json
            ./outputs/wiki-200.json
            ./outputs/teste.json